#!/usr/bin/env python3
"""harness — 하네스(런타임) 배선의 단일 진입점.

킷의 루프는 파일·CLI·훅으로 되어 있고, 하네스는 그 루프를 어떤 이벤트에 걸지만 정한다.
이 파일이 **어떤 하네스가 어떤 역할을 어떻게 받는지**의 정본이다. 런타임 어휘(다른 파일의
consumer 이름 등)는 `RUNTIMES` 한 항목에서 파생된다. 새 하네스의 어댑터 코드·테스트·배포
메타데이터(review manifest·test matrix·번역 목록)는 여전히 따로 붙여야 한다.

    harness.py status                 어떤 하네스가 설치·배선돼 있고 어떤 역할이 비었나
    harness.py install <runtime>      이 인스턴스에 배선을 깐다 (opencode는 생성)
    harness.py check                  생성된 슬래시 명령이 정본과 같은지 (모델 호출 없음, 낡으면 exit 1)
    harness.py refresh                주입용 상태 파일만 다시 굽는다 (명령 파일은 안 건드린다)
    harness.py verify <runtime>       카나리 왕복 — 주입이 **모델에 실제로 닿았는지** 실측
    harness.py open <runtime> [...]   상태를 굽고 하네스를 띄운다

역할(role)은 hookdiag.ROLE_EVENTS의 6종과 같은 이름을 쓴다. 하네스마다 받을 수 있는 역할이
다르고, **못 받는 역할은 숨기지 않고 gap으로 출력한다** (Codex가 이미 그런 상태다).
"""

import argparse
import datetime
import json
import os
import pathlib
import re
import subprocess
import sys
import tempfile
import uuid

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import memlib as M  # noqa: E402


ROOT = pathlib.Path(M.ROOT)
KIT = pathlib.Path(__file__).resolve().parent.parent

# 역할 사다리. hookdiag.ROLE_EVENTS와 같은 어휘를 쓴다 (거기는 이벤트명, 여기는 무엇을 돌리나).
ROLES = {
    "injector": "세션 시작에 상태를 주입한다",
    "recovery": "프롬프트마다 게이트를 회복한다",
    "observer": "편집 후 게이트를 더럽힌다",
    "enforcer": "멈추기 전에 게이트를 검사한다",
    "side_effect": "컴팩션을 기록한다",
    "guard": "도구 실행 전에 개입한다",
}

# opencode 슬래시 명령의 정본은 .claude/commands/<name>.md 다. 설명만 여기서 붙인다.
COMMANDS = {
    "now": "상태 정본(public NOW + local overlay)을 읽고 요약한다",
    "recall": "과거 대화 원문을 회상한다",
    "dossier": "깊은 스레드의 서류철을 읽는 복귀 의식",
    "garden": "정원사 패스(report-only)를 돌린다",
}

# 주입 파일은 인스턴스 루트에 둔다. 2026-09-21 실측: 루트 파일은 세션에 닿았고
# `.opencode/` 안의 같은 파일은 닿지 않았다 (카나리 ABSENT). 설정 디렉토리는 instructions의
# 상대경로 뿌리가 아니다.
OPENCODE_STATE = "kit-state.md"
OPENCODE_STATE_NAME = "kit-state.md"
OPENCODE_GITIGNORE_LINE = "/kit-state.md"
OPENCODE_COMMAND_DIR = ".opencode/command/"
# 모델별 판정 원장. nonce는 절대 안 들어간다 (hook_canary와 같은 규칙).
# 선택 생성물이다: `verify`를 한 번도 안 돌린 인스턴스에는 없다. 읽는 소비자는 아직 없다.
CANARY_LEDGER = "state/harness-canary.json"
GENERATED = "<!-- generated by tools/harness.py — 손으로 고치지 말 것 -->"
DEFAULT_OPENCODE_MODEL = "opencode/nemotron-3.5-lightning-free"

RUNTIMES = {
    # 배선이 레포에 체크인돼 있는 하네스: install은 배선 유무만 판정한다.
    "claude": {
        "bin": "claude",
        "wiring": [".claude/settings.json", ".claude/commands/"],
        "mode": "checked-in",
        "roles": ("injector", "recovery", "observer", "enforcer", "side_effect"),
        "gap_note": "guard(PreToolUse)는 인스턴스 재량이다",
    },
    "codex": {
        "bin": "codex",
        "wiring": [".codex/hooks.json"],
        "mode": "checked-in",
        "roles": ("injector", "side_effect"),
        "gap_note": "recovery·observer·enforcer는 Codex 훅 표면이 없어 미배선 (doctor가 WARN)",
    },
    # 생성형 하네스: install이 파일을 만든다.
    # 2026-09-21 실측으로 좁힌 주장: AGENTS.md는 세션마다 자동으로 읽힌다(watcher 로그).
    # 반면 `instructions` 항목은 v2.0.11에서 로드되지 않는다 — 띄운 직후 파일을 지우고 물었더니
    # 도구 사용 0으로 ABSENT였고, watcher가 그 파일을 한 번도 잡지 않았다. 문서·스키마와 다르다.
    # 그래서 injector는 런처가 상태를 첫 프롬프트로 심는 경로만 인정한다(`harness.py open`).
    "opencode": {
        "bin": "opencode",
        # 상태 파일만 있고 명령 디렉토리가 없으면 반쪽 배선이다. status는 여기에 더해 parity도 본다.
        "wiring": [OPENCODE_STATE, OPENCODE_COMMAND_DIR],
        "mode": "generated",
        "roles": ("injector",),
        "gap_note": ("injector는 런처(`harness.py open opencode`) 경로에서만 선다 — 직접 띄운 세션엔 "
                     "상태가 안 들어간다. recovery·observer·enforcer·side_effect·guard는 v2 플러그인 "
                     "API가 필요하고 시그니처가 아직 고정되지 않았다 — 미배선"),
    },
}


# --- 공용 ---------------------------------------------------------------

def _run(cmd, **kw):
    kw.setdefault("capture_output", True)
    kw.setdefault("text", True)
    return subprocess.run(cmd, **kw)


def which(binary):
    """PATH + opencode 기본 설치 경로까지 본다 (설치 직후 PATH가 아직 안 잡힌 셸 대응)."""
    found = _run(["/usr/bin/which", binary]).stdout.strip()
    if found:
        return found
    fallback = pathlib.Path.home() / f".{binary}" / "bin" / binary
    return str(fallback) if fallback.is_file() and os.access(fallback, os.X_OK) else ""


def atomic_write(path, content):
    path = pathlib.Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=path.name + ".", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.replace(temporary, str(path))
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def git_ignored(relpath):
    """이 경로가 확실히 Git 밖인가. 판정 불가면 False — 개인 상태는 fail-close 한다."""
    proc = _run(["git", "-C", str(ROOT), "check-ignore", "-q", relpath])
    return proc.returncode == 0


# --- opencode 어댑터 ------------------------------------------------------

def command_source(name):
    """슬래시 명령의 정본. 로케일 변형이 있으면 그것을 쓴다 (i18n과 같은 규칙)."""
    base = ROOT / ".claude" / "commands"
    localized = base / f"{name}.ko.md" if _lang() == "ko" else None
    if localized and localized.is_file():
        return localized
    return base / f"{name}.md"


def _lang():
    return (os.environ.get("MOTTORI_LANG") or "ko").split("_")[0].lower()


def render_command(name, body):
    """하나의 정본에서 opencode용 슬래시 명령을 만든다 (skill_adapters와 같은 계약)."""
    if not body.endswith("\n"):
        body += "\n"
    return (f"---\ndescription: {COMMANDS[name]}\n---\n\n{GENERATED}\n\n" + body)


def render_state(public_only=False):
    """주입할 상태 본문. 실패해도 세션은 떠야 하므로 실패 사유를 본문에 적는다."""
    env = dict(os.environ, MOTTORI_INSTANCE=str(ROOT))
    proc = _run([sys.executable, str(KIT / "tools" / "now.py"),
                 "context", "--public-only" if public_only else "--merged"], env=env)
    if proc.returncode != 0 or not proc.stdout.strip():
        detail = (proc.stderr or "").strip()[:400]
        return (f"{GENERATED}\n\n# 킷 상태 주입 실패\n\n"
                f"`tools/now.py context`가 실패했다: {detail or 'no output'}\n"
                "`python3 tools/doctor.py`로 진단하고, 그동안은 `state/NOW.md`와 "
                "존재할 때 `_private/state/NOW.md`를 직접 읽어라. "
                "local overlay 부재는 unavailable이지 상태 없음이 아니다.\n")
    return f"{GENERATED}\n\n{proc.stdout}"


def opencode_command_artifacts():
    """슬래시 명령 생성물 (경로, 내용). 상태 파일과 달리 시간에 따라 안 바뀌므로 parity를 잴 수 있다."""
    out = []
    for name in COMMANDS:
        source = command_source(name)
        if not source.is_file():
            continue
        out.append((ROOT / OPENCODE_COMMAND_DIR / f"{name}.md",
                    render_command(name, source.read_text(encoding="utf-8"))))
    return out


def opencode_artifacts(public_only):
    """생성해야 할 (경로, 내용) 목록. install이 쓴다.

    `opencode.json`은 만들지 않는다 — `instructions`가 로드되지 않는 것을 실측했으므로,
    쓰면 "배선돼 있다"처럼 보이는 죽은 줄이 된다.
    """
    return opencode_command_artifacts() + [(ROOT / OPENCODE_STATE, render_state(public_only=public_only))]


def opencode_parity():
    """생성물이 정본과 어긋난 목록. check와 status가 같은 함수를 쓴다 (모델 호출 없음).

    상태 파일은 시간에 따라 바뀌므로 내용이 아니라 존재만 본다. 신선도는 refresh·verify가 본다.
    """
    stale = []
    for path, content in opencode_command_artifacts():
        rel = path.relative_to(ROOT).as_posix()
        if not path.exists():
            stale.append(f"MISSING {rel}")
        elif path.read_text(encoding="utf-8") != content:
            stale.append(f"STALE   {rel}")
    if not (ROOT / OPENCODE_STATE).exists():
        stale.append(f"MISSING {OPENCODE_STATE}")
    return stale


def install_opencode(args):
    ensured = ensure_ignore_line()
    public_only = not git_ignored(OPENCODE_STATE)
    written = []
    for path, content in opencode_artifacts(public_only):
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        atomic_write(path, content)
        written.append(path.relative_to(ROOT).as_posix())

    print(f"opencode 배선: {ROOT}")
    for rel in written:
        print(f"  WROTE {rel}")
    if not written:
        print("  (변경 없음 — 이미 최신)")
    if ensured:
        print(f"  WROTE .gitignore (+{OPENCODE_GITIGNORE_LINE})")
    if public_only:
        print("  ⚠ 상태 파일이 Git 밖이라고 보증되지 않아 **public 상태만** 주입한다 (fail-close).")
        print(f"    개인 overlay까지 주입하려면 .gitignore에 `{OPENCODE_GITIGNORE_LINE}`를 넣어라.")
    else:
        print("  상태 파일은 Git 밖이다 — public + local overlay 주입.")
    missing = sorted(set(ROLES) - set(RUNTIMES["opencode"]["roles"]))
    print(f"  gap: {', '.join(missing)} — {RUNTIMES['opencode']['gap_note']}")
    print("  미확인: 슬래시 명령 등록 — v2 introspection이 프로젝트 범위로 안 열려 확인 못 했다.")
    print("    세션에서 `/now`가 보이는지 확인하고, 안 보이면 이 줄이 미결 작업이다.")
    print("  다음: python3 tools/harness.py open opencode   (상태를 심고 띄운다)")
    print("        python3 tools/harness.py verify opencode  (그 주입이 모델에 닿는지 실측)")
    return 0


def ensure_ignore_line():
    """인스턴스 .gitignore에 상태 파일 한 줄을 보장한다. 이미 Git 밖이면 손대지 않는다."""
    if git_ignored(OPENCODE_STATE):
        return False
    path = ROOT / ".gitignore"
    text = path.read_text(encoding="utf-8") if path.is_file() else ""
    if OPENCODE_GITIGNORE_LINE in text.splitlines():
        return False
    block = ("\n# opencode 세션 주입용 생성물 — local overlay를 담을 수 있어 Git 밖에 둔다 (harness.py)\n"
             f"{OPENCODE_GITIGNORE_LINE}\n")
    atomic_write(path, (text.rstrip("\n") + "\n" if text else "") + block)
    return True


# --- 명령 ----------------------------------------------------------------

def runtime_wiring(spec):
    """(없는 배선 경로, 생성물 parity 어긋남). 생성형은 파일 존재만으로 배선됨이라 하지 않는다."""
    missing = [w for w in spec["wiring"] if not (ROOT / w).exists()]
    stale = opencode_parity() if (not missing and spec["mode"] == "generated") else []
    return missing, stale


def cmd_status(args):
    rows = []
    for name, spec in RUNTIMES.items():
        binary = which(spec["bin"])
        missing, stale = runtime_wiring(spec)
        rows.append((name, binary, missing, stale, spec))

    width = max(len(r[0]) for r in rows)
    print(f"인스턴스: {ROOT}")
    for name, binary, missing, stale, spec in rows:
        covered = spec["roles"]
        gaps = sorted(set(ROLES) - set(covered))
        wired = not missing and not stale
        partial = bool(missing) and len(missing) < len(spec["wiring"])
        if wired:
            state = "배선됨"
        elif not missing:
            state = "배선 낡음"
        elif partial:
            state = "반쪽 배선"
        else:
            state = "미배선" if binary else "미설치"
        mark = "OK  " if (binary and wired) else ("TODO" if binary else "--  ")
        print(f"{mark} {name.ljust(width)}  {state}  "
              f"역할 {len(covered)}/{len(ROLES)}  ({spec['mode']})")
        for line in ([f"MISSING {w}" for w in missing] if partial else []) + stale:
            print(f"       {line}")
        if spec["mode"] == "generated" and not missing:
            scope = ("Git 밖 — public + local overlay 주입" if git_ignored(OPENCODE_STATE)
                     else "Git 밖 미증명 — public 상태만 주입 (fail-close)")
            print(f"       상태 파일: {scope}")
        if binary and not wired:
            hint = ("python3 tools/harness.py install " + name) if spec["mode"] == "generated" \
                else f"배선 파일이 레포에 없다: {', '.join(missing) or ', '.join(spec['wiring'])}"
            print(f"       → {hint}")
        if gaps:
            print(f"       gap: {', '.join(gaps)} — {spec['gap_note']}")
    return 0


def cmd_install(args):
    spec = RUNTIMES[args.runtime]
    if spec["mode"] != "generated":
        wired = [w for w in spec["wiring"] if (ROOT / w).exists()]
        missing = [w for w in spec["wiring"] if not (ROOT / w).exists()]
        print(f"{args.runtime}: 배선은 레포에 체크인돼 있다 (생성 대상 아님).")
        for w in wired:
            print(f"  OK   {w}")
        for w in missing:
            print(f"  MISS {w}")
        return 1 if missing else 0
    return install_opencode(args)


def cmd_check(args):
    """모델 호출 없이 생성물 parity만 본다. CI·doctor가 부를 자리.

    opencode를 한 번도 install하지 않은 인스턴스는 검사 대상이 아니다 (PASS).
    """
    if not any((ROOT / w).exists() for w in RUNTIMES["opencode"]["wiring"]):
        print("-- opencode 미배선 (검사 대상 없음)")
        return 0
    stale = opencode_parity()
    for line in stale:
        print(line)
    if stale:
        print("→ python3 tools/harness.py install opencode")
        return 1
    print("PASS opencode 생성물 parity")
    return 0


def cmd_refresh(args):
    public_only = not git_ignored(OPENCODE_STATE)
    content = render_state(public_only=public_only)
    atomic_write(ROOT / OPENCODE_STATE, content)
    scope = "public만" if public_only else "public + local overlay"
    print(f"상태 재생성: {OPENCODE_STATE} ({len(content.encode('utf-8'))} bytes, {scope})")
    return 0


def available_models(binary):
    """이 설치가 실제로 부를 수 있는 모델 목록. 로그인한 제공자가 늘면 여기도 늘어난다."""
    proc = _run([binary, "models"], cwd=str(ROOT))
    return [line.strip() for line in (proc.stdout or "").splitlines()
            if line.strip() and "/" in line.strip()]


def canary_once(binary, model, timeout):
    """모델 하나를 잰다. (verdict, detail) 반환. verdict: pass|fail|inconclusive|refused|timeout.

    nonce는 실행 동안만 주입 파일(kit-state.md, Git 밖)에 있다 — 그 파일을 첨부로 보내는 것이
    재려는 채널이기 때문이다. 실행이 끝나면(타임아웃·예외 포함) finally가 nonce 없는 본문으로
    덮어쓰고, 원장에는 판정만 남는다. 판정 규칙은 read_stream의 docstring 참고.
    """
    nonce = "KIT-" + uuid.uuid4().hex[:10].upper()
    public_only = not git_ignored(OPENCODE_STATE)
    os.environ["MOTTORI_HOOK_CANARY"] = nonce
    atomic_write(ROOT / OPENCODE_STATE, render_state(public_only=public_only))

    # 상태를 첨부로 붙인다. `instructions` 경로는 v2.0.11에서 로드되지 않는 것이 실측됐고,
    # `open`이 쓰는 것과 같은 파일이라 이 왕복이 그 채널을 그대로 잰다.
    cmd = [binary, "run", "--standalone", "-m", model, "--format", "json",
           "-f", str(ROOT / OPENCODE_STATE),
           "Print only the value that follows HOOK_CANARY: in the attached state. "
           "No other words. If it is absent, print ABSENT."]
    try:
        proc = _run(cmd, cwd=str(ROOT), timeout=timeout)
    except subprocess.TimeoutExpired:
        return "timeout", f"{timeout:.0f}s 안에 응답 없음"
    finally:
        os.environ.pop("MOTTORI_HOOK_CANARY", None)
        atomic_write(ROOT / OPENCODE_STATE, render_state(public_only=public_only))

    text, tools, errors = read_stream(proc.stdout)
    if errors:
        return "refused", errors[0][:160]
    if tools:
        return "inconclusive", "도구 사용: " + ", ".join(sorted(set(tools)))
    if nonce in text:
        return "pass", "도구 사용 0"
    return "fail", (text.strip()[:120] or "(빈 응답)")


def persist_canary(rows, path=None):
    """판정과 시각만 남긴다. 원장에 nonce를 보존하지 않는다 (hook_canary와 같은 규칙)."""
    path = pathlib.Path(path or (ROOT / CANARY_LEDGER))
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        if payload.get("schema_version") != 1 or not isinstance(payload.get("models"), dict):
            raise ValueError
    except (OSError, ValueError):
        payload = {"schema_version": 1, "models": {}}
    stamp = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    for model, (verdict, detail) in rows.items():
        payload["models"][model] = {"checked_at": stamp, "verdict": verdict, "detail": detail}
    atomic_write(path, json.dumps(payload, ensure_ascii=False, indent=2) + "\n")
    return path


def cmd_verify(args):
    """카나리 왕복. 주입이 '설정에 있다'가 아니라 '모델이 봤다'를 재는 유일한 방법이다.

    `--sweep`는 부를 수 있는 모델을 전부 돌며 표를 만든다. 온디맨드로 모델을 갈아탈 때
    "이 모델이 킷 상태를 실제로 받아서 따르나"를 모델마다 따로 알아야 하기 때문이다.
    """
    if args.runtime != "opencode":
        print(f"{args.runtime} 카나리는 tools/hook_canary.py가 담당한다.")
        return 2
    binary = which("opencode")
    if not binary:
        print("opencode가 없다. 설치 후 다시 실행해라.")
        return 2

    models = available_models(binary) if args.sweep else [args.model]
    if not models:
        print("부를 수 있는 모델이 없다. `opencode auth login` 먼저.")
        return 2

    rows = {}
    for model in models:
        verdict, detail = canary_once(binary, model, args.timeout)
        rows[model] = (verdict, detail)
        mark = {"pass": "PASS", "fail": "FAIL", "inconclusive": "INCONC",
                "refused": "REFUSED", "timeout": "TIMEOUT"}[verdict]
        print(f"{mark:8} {model}  {detail}")
    ledger = persist_canary(rows)
    passed = sum(1 for v, _ in rows.values() if v == "pass")
    print(f"\n{passed}/{len(rows)} 모델이 킷 상태를 받았다 · 원장 {ledger.relative_to(ROOT).as_posix()}")
    if passed == 0:
        print("  판정 불가·거부가 전부면 주입이 아니라 모델·티어 문제일 수 있다.")
    return 0 if passed else 1


def read_stream(stream):
    """모델 답변·도구 호출·오류를 나눠 읽는다.

    도구 호출을 따로 세는 이유: 주입 본문이 **파일**인 하네스에서는 모델이 grep·read로 같은
    파일을 찾아 주입 없이도 nonce를 답할 수 있다 (2026-09-21 실측: 첫 실험이 그렇게 오염됐다).
    도구를 껐더니 무료 티어가 실행을 거부해서(403), 끄는 대신 **도구를 쓴 실행은 PASS로 세지
    않는다**. 증거가 약해지는 쪽이 아니라 판정을 유보하는 쪽으로 실패한다.
    """
    text, tools, errors = [], [], []
    for line in (stream or "").splitlines():
        line = line.strip()
        if not line.startswith("{"):
            continue
        try:
            event = json.loads(line)
        except ValueError:
            continue
        kind = event.get("type")
        part = event.get("part") or {}
        if kind == "text":
            text.append(str(part.get("text", "")))
        elif kind == "tool_use":
            tools.append(str(part.get("tool", "?")))
        elif kind == "error":
            errors.append(str((event.get("error") or {}).get("message", "error")))
    return "\n".join(text), tools, errors


def seed_prompt(state):
    return ("아래는 킷이 이 세션에 심은 현재 상태다. 대화 맥락과 충돌하면 이것이 정본이다.\n"
            "요약·기억이 아니라 이 본문을 근거로 삼아라.\n\n" + state)


def cmd_open(args):
    """상태를 굽고 하네스를 띄운다. opencode는 첫 프롬프트로 상태를 심는다.

    훅이 없는 하네스에서 유일하게 확인된 주입 경로다. 대가가 있다: 세션이 뜨자마자 한 턴을
    쓴다. 직접 `opencode`를 친 세션에는 상태가 안 들어간다 — 그건 gap으로 선언돼 있다.
    """
    binary = which(args.runtime)
    if not binary:
        print(f"{args.runtime}가 PATH에 없다.")
        return 2
    if args.runtime != "opencode":
        os.execv(binary, [binary] + args.rest)
    cmd_refresh(args)
    state = (ROOT / OPENCODE_STATE).read_text(encoding="utf-8")
    os.execv(binary, [binary, "--prompt", seed_prompt(state)] + args.rest)


def main(argv=None):
    parser = argparse.ArgumentParser(description="하네스 배선의 단일 진입점")
    sub = parser.add_subparsers(dest="cmd", required=True)

    sub.add_parser("status", help="설치·배선·역할 커버리지").set_defaults(func=cmd_status)

    p_install = sub.add_parser("install", help="이 인스턴스에 배선을 깐다")
    p_install.add_argument("runtime", choices=sorted(RUNTIMES))
    p_install.set_defaults(func=cmd_install)

    sub.add_parser("check", help="생성물 parity (모델 호출 없음)").set_defaults(func=cmd_check)
    sub.add_parser("refresh", help="주입용 상태 파일 재생성").set_defaults(func=cmd_refresh)

    p_verify = sub.add_parser("verify", help="카나리 왕복 실측")
    p_verify.add_argument("runtime", choices=sorted(RUNTIMES))
    p_verify.add_argument("--model", default=os.environ.get("MOTTORI_OPENCODE_MODEL", DEFAULT_OPENCODE_MODEL))
    p_verify.add_argument("--sweep", action="store_true", help="부를 수 있는 모델을 전부 잰다")
    p_verify.add_argument("--timeout", type=float, default=300.0)
    p_verify.set_defaults(func=cmd_verify)

    p_open = sub.add_parser("open", help="상태를 굽고 하네스를 띄운다")
    p_open.add_argument("runtime", choices=sorted(RUNTIMES))
    p_open.add_argument("rest", nargs=argparse.REMAINDER)
    p_open.set_defaults(func=cmd_open)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
