#!/usr/bin/env python3
"""Generate deterministic runtime adapters from a canonical workflow."""

import argparse
import hashlib
import os
import pathlib
import tempfile


ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = ROOT / "system" / "skills" / "paper-to-kit.md"
CANONICAL_BEGIN = "<!-- BEGIN CANONICAL WORKFLOW -->"
CANONICAL_END = "<!-- END CANONICAL WORKFLOW -->"


def read_source(path):
    text = pathlib.Path(path).read_text(encoding="utf-8")
    if not text.endswith("\n"):
        raise ValueError("canonical workflow must end with a newline")
    return text


def source_label(path):
    path = pathlib.Path(path).resolve()
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def render_adapter(runtime, source_text, label):
    digest = hashlib.sha256(source_text.encode("utf-8")).hexdigest()
    common = (
        f"<!-- generated by tools/skill_adapters.py from {label}; sha256:{digest} -->\n"
    )
    if runtime == "claude":
        preamble = (
            common
            + "아래 정본 workflow v1을 따라 논문에서 킷 제안을 만들어줘. 입력은 \"$ARGUMENTS\"다.\n"
            + "정본의 사람 판정 게이트와 킷 파일 수정 0건 경계를 지켜라.\n\n"
        )
    elif runtime == "codex":
        preamble = (
            "---\n"
            "name: paper-to-kit\n"
            "description: Turn a paper list or source URL and period into evidence-tagged, "
            "experiment-ready kit proposals without modifying the kit.\n"
            "---\n\n"
            + common
            + "Use the canonical workflow below when asked to review papers for changes the kit "
            "should consider. Preserve its human gate and zero kit-write boundary.\n\n"
        )
    else:
        raise ValueError("unsupported runtime: " + runtime)
    return preamble + CANONICAL_BEGIN + "\n" + source_text + CANONICAL_END + "\n"


def extract_canonical(adapter_text):
    start = CANONICAL_BEGIN + "\n"
    if adapter_text.count(start) != 1 or adapter_text.count(CANONICAL_END) != 1:
        raise ValueError("adapter canonical markers are missing or ambiguous")
    return adapter_text.split(start, 1)[1].rsplit(CANONICAL_END, 1)[0]


def atomic_write(path, content):
    path = pathlib.Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=path.name + ".", dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.replace(temporary, str(path))
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate or check one runtime adapter from the canonical paper-to-kit workflow."
    )
    parser.add_argument("runtime", choices=("claude", "codex"))
    parser.add_argument("output", help="adapter file path; Codex location is supplied by the caller")
    parser.add_argument("--source", default=str(DEFAULT_SOURCE))
    parser.add_argument("--check", action="store_true", help="check exact parity without writing")
    args = parser.parse_args(argv)

    source = pathlib.Path(args.source).resolve()
    output = pathlib.Path(args.output).resolve()
    if source == output:
        parser.error("output must not overwrite the canonical workflow")
    expected = render_adapter(args.runtime, read_source(source), source_label(source))

    if args.check:
        try:
            actual = output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"STALE {output}: missing")
            return 1
        if actual != expected:
            print(f"STALE {output}: regenerate from {source_label(source)}")
            return 1
        print(f"PASS {args.runtime} parity: {output}")
        return 0

    atomic_write(output, expected)
    print(f"WROTE {args.runtime} adapter: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
